### ISSUE TITLE
Investigate what sampler_type means and why this is unknown during check-traces tests

### ISSUE THREAD

**Issue by helio-frota** [obs-nebula/check-traces#4]
This is the current result we have when running the CI tests on check-traces repository:

```
jaeger_traces_saved_by_svc_total{debug="false",result="ok",sampler_type="unknown",svc="check-traces"} 1
```

**Comment by helio-frota** [comment]
@pnaik1 I found these things in case you can find an answer faster than me:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#built-in-samplers

https://www.jaegertracing.io/docs/1.39/sampling/

https://opentelemetry.io/docs/reference/specification/trace/tracestate-probability-sampling/

**Comment by pnaik1** [comment]
https://github.com/jaegertracing/jaeger/issues/2197 I think may be this will help

**Comment by helio-frota** [comment]
@pnaik1 that helps a lot thanks.

After read that issue you shared, I could bet that the `otel js` modules we are using have nothing to do with that unknown value. [ ? ]  (very specific to Jaeger seems like we need that `sampling-strategies.json`)

Let's keep this issue open then. 
We can take a look later  at some point in 2023 :+1:

**Comment by helio-frota** [comment]
> We can take a look later at some point in 2023

Taking a look in 2023 :+1: 

```
In distributed tracing, sampling is frequently used to reduce the number of traces 
that are collected and stored in the backend. 
This is often desirable because it is easy to produce more data than can be 
efficiently stored and queried. 
Sampling allows us to store only a subset of the total traces produced.
```
https://medium.com/jaegertracing/adaptive-sampling-in-jaeger-50f336f4334#:~:text=Sampling%20allows%20us%20to%20store,source%20by%20the%20Jaeger%20project.

We don't need to worry about that for this repository.

Either way I found this comment: https://github.com/open-telemetry/opentelemetry-js/issues/693#issuecomment-574001038
